# Site settings
title: Deep Musings
email: 
description: > # this means to ignore newlines until "baseurl:"
  My learnings on Deep Learning
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jmohamedzahoor 
github_username: jmozah        

# Build settings
markdown: kramdown
